apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-turn-on-network-diags
  namespace: default
spec:
  clusterLabelSelectors:
    - matchLabels:
        vendor: OpenShift
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 1
  enable: true
