apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test-disabled-cgu
  namespace: default
spec:
  clusters:
    - local-cluster
    - spoke1-sno
    - spoke2-sno
    - spoke3-sno
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 1
    timeout: 30
  enable: false 
