apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: network-diagnostic-policy-on
  namespace: default
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: network-diagnostic-policy-on-config
      spec:
        namespaceselector:
          exclude:
          - kube-*
          include:
          - '*'
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: operator.openshift.io/v1
            kind: Network
            metadata:
              name: cluster
            spec:
              disableNetworkDiagnostics: false
        remediationAction: inform
        severity: low
  remediationAction: inform
