apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-apply-conflicting-policies
  namespace: default
spec:
  clusterLabelSelectors:
    - matchLabels:
        vendor: OpenShift
  managedPolicies:
  - network-diagnostic-policy-on
  - network-diagnostic-policy-off
  remediationStrategy:
    maxConcurrency: 1
    timeout: 20
  enable: true
