apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-cluster-version
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: upgrade-policy
        spec:
          namespaceselector:
            exclude:
              - kube-*
            include:
              - "*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  channel: stable-4.10
                  upstream: http://mirror-webserver-default.apps.hub.karmalabs.com/bz2089976-graph.json 
                  desiredUpdate:
                    force: false
                    version: 4.10.24
          remediationAction: inform
          severity: low
  remediationAction: inform
