apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-cluster-version
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: upgrade-policy
        spec:
          namespaceselector:
            exclude:
              - kube-*
            include:
              - "*"
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  clusterID: '{{ (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.clusterID }}'
                  channel: '{{ (lookup "config.openshift.io/v1" "ClusterVersion" "" "version").spec.channel }}'
          remediationAction: inform
          severity: low
  remediationAction: inform
