apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: openshift-cluster-version
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: upgrade-policy
        spec:
          namespaceselector:
            exclude:
              - kube-*
            include:
              - "*"
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterVersion
                metadata:
                  name: version
                spec:
                  channel: stable-4.10
                  desiredUpdate:
                    image: quay.io/openshift-release-dev/ocp-release@sha256:195de2a5ef3af1083620a62a45ea61ac1233ffa27bbce7b30609a69775aeca19
                    version: 4.10.18
          remediationAction: inform
          severity: low
  remediationAction: inform

