apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: openshift-cluster-version
  namespace: default
spec:
  description: ""
  policies:
    - openshift-cluster-version
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: openshift-cluster-version-placement
  namespace: default
spec:
  clusterSelector:
    matchExpressions: []
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-cluster-version-placement
  namespace: default
placementRef:
  name: openshift-cluster-version-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: openshift-cluster-version
    apiGroup: policy.open-cluster-management.io
    kind: PolicySet

