apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-turn-on-network-diags
  namespace: default
spec:
  clusters:
    - local-cluster
  clusterSelector:
    - openshiftVersion=4.10.20
  clusterLabelSelectors:
    - matchLabels:
        name: spoke3
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 10 
  enable: true
