apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-turn-on-network-diags
  namespace: default
spec:
  clusterLabelSelectors:
    - matchExpressions:
        - key: openshiftVersion
          operator: In
          values:
            - 4.10.20
            - 4.9.38
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 10 
  enable: true
