apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-turn-on-network-diags
  namespace: default
spec:
  clusterLabelSelectors:
    - matchLabels:
        openshiftVersion: 4.10.20
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 3 
  enable: true
