apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test-missing-policy-cgu
  namespace: default
spec:
  clusters:
    - local-cluster
  managedPolicies:
  - non-existant-policy
  remediationStrategy:
    maxConcurrency: 1
    timeout: 30
  enable: true 
