apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: test-upgrade-with-backup-cgu
  namespace: default
spec:
  clusters:
    - local-cluster
  managedPolicies:
  - network-diagnostic-policy
  remediationStrategy:
    maxConcurrency: 1
  timeout: 10
  backup: true
  enable: true 
